### ISSUE TITLE
Uncaught Error: Cannot find module './components/app'

### ISSUE THREAD

**Issue by mojtabadarzi** [LaurenceHo/react-weather-app#1]
Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
main.bundle.js:38668 [HMR] Waiting for update signal from WDS...
main.bundle.js:39267 Uncaught Error: Cannot find module './components/app'
    at webpackMissingModule (main.bundle.js:39267)
    at Module../src/index.tsx (main.bundle.js:39267)
    at __webpack_require__ (main.bundle.js:724)
    at fn (main.bundle.js:101)
    at Object.0 (main.bundle.js:39414)
    at __webpack_require__ (main.bundle.js:724)
    at main.bundle.js:791
    at main.bundle.js:794
main.bundle.js:37991 [WDS] Hot Module Replacement enabled.
main.bundle.js:38076 [WDS] Errors while compiling. Reload prevented.
errors @ main.bundle.js:38076
main.bundle.js:38082 ./src/index.tsx
Module not found: Error: Can't resolve './components/app' in '/home/x/Desktop/reactjs-beautiful-weather/src'
errors @ main.bundle.js:38082
main.bundle.js:38082 /home/x/Desktop/reactjs-beautiful-weather/src/index.tsx
./src/index.tsx
[tsl] ERROR in /home/x/Desktop/reactjs-beautiful-weather/src/index.tsx(17,21)
      TS2307: Cannot find module './components/app'.
errors @ main.bundle.js:38082

**Comment by LaurenceHo** [comment]
Hi, when I opened this link (https://react-beautiful-weather-app.firebaseapp.com/) directly on Google Chrome, I can access this link without having any problem, although I can see this Google Chrome complaint in the console. Even though I open the link in the Safari, I still cannot reproduce this error you showed me above.
