### ISSUE TITLE
Error serving from undefined

### ISSUE THREAD

**Issue by johnnyhliang** [LaurenceHo/react-weather-app#11]
｢wds｣: webpack output is served from undefined
｢wds｣: Content not from webpack is served from ../dist
｢wds｣: 404s will fallback to /index.html

^^^^^^^^^^^
webpack output

Im not sure if this is causing the fetch errors, because I'm sure my api keys are valid, I did some fetch testing. I was using 

 `npm run start` trying to host it locally, not deploying it yet

btw this is awesome

**Comment by johnnyhliang** [comment]
nvm im such an idiot didnt start server :( i apologize for wasting space and time on this issue thread

**Comment by LaurenceHo** [comment]
All good, thanks for the comment. It's just my personal project, if you have any question, please let me know.
